name: Build Bro
on: push

jobs:
  compile-script:
    name: Compile Bro's main script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run PowerShell script
        shell: pwsh
        run: ./Build.ps1
      - name: Push the compiled script
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Build Bro'
